#!/usr/bin/dotnet --
#:property EnablePreviewFeatures=true
#:property NoWarn=CA1303;CA2007

// Converts Yoga's generated C++ gtest files (tests/generated/YG*Test.cpp) into
// C# Fixie tests under test/timewarp-flexbox-tests/Generated/.
//
// Usage: ./runfiles/port-generated-tests.cs <yoga-repo-path> <TestName>...
// Example: ./runfiles/port-generated-tests.cs ~/repos/github.com/facebook/yoga FlexDirection JustifyContent
//
// Tests containing constructs the port does not support yet (experimental
// features, measure functions, ...) are skipped and reported so they can be
// ported by hand later.

using System.Text;
using System.Text.RegularExpressions;

if (args.Length < 2)
{
  Console.WriteLine("Usage: port-generated-tests.cs <yoga-repo-path> <TestName>...");
  return 1;
}

string yogaRepo = args[0];
string repoRoot = Path.GetFullPath(Path.Combine(AppContext.BaseDirectory, "..", "..", ".."));
// When run via `dotnet run`, BaseDirectory points into an artifacts dir; fall back to CWD.
if (!Directory.Exists(Path.Combine(repoRoot, "test")))
{
  repoRoot = Directory.GetCurrentDirectory();
}

string outputDir = Path.Combine(repoRoot, "test", "timewarp-flexbox-tests", "Generated");
Directory.CreateDirectory(outputDir);

int exitCode = 0;
foreach (string name in args.Skip(1))
{
  string sourcePath = Path.Combine(yogaRepo, "tests", "generated", $"YG{name}Test.cpp");
  if (!File.Exists(sourcePath))
  {
    Console.WriteLine($"ERROR: {sourcePath} not found");
    exitCode = 1;
    continue;
  }

  ConversionResult result = Converter.ConvertFile(sourcePath, name);
  string outputPath = Path.Combine(outputDir, $"{name}Tests.cs");
  File.WriteAllText(outputPath, result.Output);
  Console.WriteLine($"{name}: {result.Converted} tests converted, {result.Skipped.Count} skipped -> {Path.GetRelativePath(repoRoot, outputPath)}");
  foreach (string skipped in result.Skipped)
  {
    Console.WriteLine($"  SKIPPED {skipped}");
  }
}

return exitCode;

internal sealed record ConversionResult(string Output, int Converted, List<string> Skipped);

internal static partial class Converter
{
  public static ConversionResult ConvertFile(string sourcePath, string name)
  {
    string[] lines = File.ReadAllLines(sourcePath);
    StringBuilder output = new();
    List<string> skipped = new();
    int converted = 0;

    output.AppendLine("/*");
    output.AppendLine(" * TimeWarp.Flexbox - C# port of Facebook Yoga");
    output.AppendLine(" *");
    output.AppendLine($" * @generated by runfiles/port-generated-tests.cs from yoga/tests/generated/YG{name}Test.cpp");
    output.AppendLine(" * (itself generated by gentest from HTML fixtures). Do not edit by hand;");
    output.AppendLine(" * re-run the converter instead.");
    output.AppendLine(" */");
    output.AppendLine();
    output.AppendLine("namespace TimeWarp.Flexbox.Tests.Generated;");
    output.AppendLine();
    output.AppendLine("using FlexNode = TimeWarp.Flexbox.Node;");
    output.AppendLine("using FlexConfig = TimeWarp.Flexbox.Config;");
    output.AppendLine();
    output.AppendLine($"public class {name}Tests");
    output.AppendLine("{");

    int i = 0;
    bool first = true;
    while (i < lines.Length)
    {
      Match testStart = TestStartRegex().Match(lines[i]);
      if (!testStart.Success)
      {
        i++;
        continue;
      }

      string testName = testStart.Groups[1].Value;

      // Collect the body up to the closing brace at column 0
      List<string> body = new();
      int j = i + 1;
      while (j < lines.Length && lines[j] != "}")
      {
        body.Add(lines[j]);
        j++;
      }

      (List<string>? translated, string? blocker) = TranslateBody(body);
      if (translated is null)
      {
        skipped.Add($"{testName} (unsupported: {blocker})");
      }
      else
      {
        if (!first)
        {
          output.AppendLine();
        }

        first = false;
        output.AppendLine($"    public void {testName}()");
        output.AppendLine("    {");
        foreach (string line in translated)
        {
          output.AppendLine(line);
        }

        output.AppendLine("    }");
        converted++;
      }

      i = j + 1;
    }

    output.AppendLine("}");
    return new ConversionResult(output.ToString(), converted, skipped);
  }

  private static (List<string>? Result, string? Blocker) TranslateBody(List<string> body)
  {
    List<string> result = new();
    foreach (string raw in body)
    {
      string line = raw.Trim();
      if (line.Length == 0)
      {
        result.Add("");
        continue;
      }

      string? translated = TranslateLine(line);
      if (translated is null)
      {
        return (null, line); // untranslatable construct: skip whole test
      }

      if (translated.Length > 0)
      {
        result.Add("        " + translated);
      }
    }

    // Collapse a trailing blank (left by dropped Free calls)
    while (result.Count > 0 && result[^1].Length == 0)
    {
      result.RemoveAt(result.Count - 1);
    }

    return (result, null);
  }

  private static string? TranslateLine(string line)
  {
    Match m;

    // Dropped lines (GC handles freeing)
    if (line.StartsWith("YGNodeFreeRecursive(", StringComparison.Ordinal) ||
        line.StartsWith("YGConfigFree(", StringComparison.Ordinal))
    {
      return "";
    }

    if (line == "YGConfigRef config = YGConfigNew();")
    {
      return "FlexConfig config = new();";
    }

    m = Regex.Match(line, @"^YGNodeRef (\w+) = YGNodeNewWithConfig\(config\);$");
    if (m.Success)
    {
      return $"FlexNode {m.Groups[1].Value} = new(config);";
    }

    m = Regex.Match(line, @"^YGNodeInsertChild\((\w+), (\w+), (\d+)\);$");
    if (m.Success)
    {
      return $"{m.Groups[1].Value}.InsertChild({m.Groups[2].Value}, {m.Groups[3].Value});";
    }

    // Enum-valued style properties
    m = Regex.Match(line, @"^YGNodeStyleSet(FlexDirection|JustifyContent|AlignItems|AlignSelf|AlignContent|PositionType|FlexWrap|Overflow|Display|Direction|BoxSizing)\((\w+), YG(\w+)\);$");
    if (m.Success)
    {
      string prop = m.Groups[1].Value;
      string node = m.Groups[2].Value;
      string? enumValue = TranslateEnumValue(prop, m.Groups[3].Value);
      return enumValue is null ? null : $"{node}.Style.{prop} = {enumValue};";
    }

    // Dimensions (Width/Height, Min/Max, Percent/Auto/values)
    m = Regex.Match(line, @"^YGNodeStyleSet(Min|Max)?(Width|Height)(Percent|Auto|MaxContent|FitContent|Stretch)?\((\w+)(?:, ([\w.+-]+))?\);$");
    if (m.Success)
    {
      string method = m.Groups[1].Value switch
      {
        "Min" => "SetMinDimension",
        "Max" => "SetMaxDimension",
        _ => "SetDimension",
      };
      string axis = m.Groups[2].Value; // Width | Height
      string? value = SizeLengthValue(m.Groups[3].Value, m.Groups[5].Value);
      return value is null ? null : $"{m.Groups[4].Value}.Style.{method}(Dimension.{axis}, {value});";
    }

    // Flex basis
    m = Regex.Match(line, @"^YGNodeStyleSetFlexBasis(Percent|Auto|MaxContent|FitContent|Stretch)?\((\w+)(?:, ([\w.+-]+))?\);$");
    if (m.Success)
    {
      string? value = SizeLengthValue(m.Groups[1].Value, m.Groups[3].Value);
      return value is null ? null : $"{m.Groups[2].Value}.Style.FlexBasis = {value};";
    }

    // Float-valued style properties
    m = Regex.Match(line, @"^YGNodeStyleSet(FlexGrow|FlexShrink|Flex|AspectRatio)\((\w+), ([\w.+-]+)\);$");
    if (m.Success)
    {
      string? value = FloatLiteral(m.Groups[3].Value);
      return value is null ? null : $"{m.Groups[2].Value}.Style.{m.Groups[1].Value} = {value};";
    }

    // Edge-valued style properties (Margin/Padding/Border/Position), point/percent/auto
    m = Regex.Match(line, @"^YGNodeStyleSet(Margin|Padding|Border|Position)(Percent|Auto)?\((\w+), YGEdge(\w+)(?:, ([\w.+-]+))?\);$");
    if (m.Success)
    {
      string prop = m.Groups[1].Value;
      string? value = LengthValue(m.Groups[2].Value, m.Groups[5].Value);
      return value is null ? null : $"{m.Groups[3].Value}.Style.Set{prop}(Edge.{m.Groups[4].Value}, {value});";
    }

    // Gap
    m = Regex.Match(line, @"^YGNodeStyleSetGap(Percent)?\((\w+), YGGutter(\w+), ([\w.+-]+)\);$");
    if (m.Success)
    {
      string? value = LengthValue(m.Groups[1].Value, m.Groups[4].Value);
      return value is null ? null : $"{m.Groups[2].Value}.Style.SetGap(Gutter.{m.Groups[3].Value}, {value});";
    }

    // Layout calculation
    m = Regex.Match(line, @"^YGNodeCalculateLayout\((\w+), ([\w.+-]+), ([\w.+-]+), YGDirection(LTR|RTL)\);$");
    if (m.Success)
    {
      string? width = FloatLiteral(m.Groups[2].Value);
      string? height = FloatLiteral(m.Groups[3].Value);
      return width is null || height is null
        ? null
        : $"CalculateLayout.Calculate({m.Groups[1].Value}, {width}, {height}, Direction.{m.Groups[4].Value});";
    }

    // Layout assertions
    m = Regex.Match(line, @"^ASSERT_FLOAT_EQ\(([\w.+-]+), YGNodeLayoutGet(Left|Top|Right|Bottom|Width|Height)\((\w+)\)\);$");
    if (m.Success)
    {
      string? expected = FloatLiteral(m.Groups[1].Value);
      if (expected is null)
      {
        return null;
      }

      string accessor = m.Groups[2].Value switch
      {
        "Width" => "GetDimension(Dimension.Width)",
        "Height" => "GetDimension(Dimension.Height)",
        var edge => $"GetPosition(PhysicalEdge.{edge})",
      };
      return $"{m.Groups[3].Value}.Layout.{accessor}.ShouldBe({expected});";
    }

    return null; // unknown construct
  }

  private static string? SizeLengthValue(string suffix, string value) => suffix switch
  {
    "Percent" => FloatLiteral(value) is string p ? $"StyleSizeLength.Percent({p})" : null,
    "Auto" => "StyleSizeLength.Auto",
    "MaxContent" => "StyleSizeLength.MaxContent",
    "FitContent" => "StyleSizeLength.FitContent",
    "Stretch" => "StyleSizeLength.Stretch",
    "" => value == "YGUndefined"
      ? "StyleSizeLength.Undefined"
      : FloatLiteral(value) is string v ? $"StyleSizeLength.Points({v})" : null,
    _ => null,
  };

  private static string? LengthValue(string suffix, string value) => suffix switch
  {
    "Percent" => FloatLiteral(value) is string p ? $"StyleLength.Percent({p})" : null,
    "Auto" => "StyleLength.Auto",
    "" => value == "YGUndefined"
      ? "StyleLength.Undefined"
      : FloatLiteral(value) is string v ? $"StyleLength.Points({v})" : null,
    _ => null,
  };

  private static string? FloatLiteral(string token)
  {
    if (token == "YGUndefined")
    {
      return "float.NaN";
    }

    string number = token.EndsWith('f') || token.EndsWith('F') ? token[..^1] : token;
    return float.TryParse(number, System.Globalization.CultureInfo.InvariantCulture, out _) ? $"{number}f" : null;
  }

  private static string? TranslateEnumValue(string property, string ygValue)
  {
    (string enumType, string prefix) = property switch
    {
      "FlexDirection" => ("FlexDirection", "FlexDirection"),
      "JustifyContent" => ("Justify", "Justify"),
      "AlignItems" or "AlignSelf" or "AlignContent" => ("Align", "Align"),
      "PositionType" => ("PositionType", "PositionType"),
      "FlexWrap" => ("Wrap", "Wrap"),
      "Overflow" => ("Overflow", "Overflow"),
      "Display" => ("Display", "Display"),
      "Direction" => ("Direction", "Direction"),
      "BoxSizing" => ("BoxSizing", "BoxSizing"),
      _ => ("", ""),
    };

    if (enumType.Length == 0 || !ygValue.StartsWith(prefix, StringComparison.Ordinal))
    {
      return null;
    }

    string member = ygValue[prefix.Length..];
    return member.Length == 0 ? null : $"{enumType}.{member}";
  }

  [GeneratedRegex(@"^TEST\(YogaTest, (\w+)\) \{$")]
  private static partial Regex TestStartRegex();
}
